services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    build: ./counter
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  library:
    build: .
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_HOST=counter
      - COUNTER_PORT=3001
    depends_on:
      - counter
