services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:latest
    volumes:
      - ./counter:/app
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    working_dir: /app
    depends_on:
      - storage
    command: ["npm", "run", "dev"]
  library:
    image: node:latest
    volumes:
      - ./:/app
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_HOST=counter
      - COUNTER_PORT=3001
    working_dir: /app
    depends_on:
      - counter
    command: ["npm", "run", "dev"]
